// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/risingwavelabs/byoc-runtime/pkg/terraform (interfaces: Executor,ExecutorFactory,Installer,HTTPClient)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/risingwavelabs/byoc-runtime/pkg/terraform -package=terraform -destination=pkg/terraform/mock_gen.go github.com/risingwavelabs/byoc-runtime/pkg/terraform Executor,ExecutorFactory,Installer,HTTPClient
//

// Package terraform is a generated GoMock package.
package terraform

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"
	time "time"

	tfexec "github.com/hashicorp/terraform-exec/tfexec"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockExecutor) Apply(ctx context.Context, opts ...tfexec.ApplyOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Apply", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockExecutorMockRecorder) Apply(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockExecutor)(nil).Apply), varargs...)
}

// Destroy mocks base method.
func (m *MockExecutor) Destroy(ctx context.Context, opts ...tfexec.DestroyOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Destroy", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Destroy indicates an expected call of Destroy.
func (mr *MockExecutorMockRecorder) Destroy(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockExecutor)(nil).Destroy), varargs...)
}

// ForceUnlock mocks base method.
func (m *MockExecutor) ForceUnlock(ctx context.Context, lockID string, opts ...tfexec.ForceUnlockOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, lockID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ForceUnlock", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceUnlock indicates an expected call of ForceUnlock.
func (mr *MockExecutorMockRecorder) ForceUnlock(ctx, lockID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, lockID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUnlock", reflect.TypeOf((*MockExecutor)(nil).ForceUnlock), varargs...)
}

// Init mocks base method.
func (m *MockExecutor) Init(ctx context.Context, opts ...tfexec.InitOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Init", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockExecutorMockRecorder) Init(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockExecutor)(nil).Init), varargs...)
}

// Output mocks base method.
func (m *MockExecutor) Output(ctx context.Context, opts ...tfexec.OutputOption) (map[string]tfexec.OutputMeta, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Output", varargs...)
	ret0, _ := ret[0].(map[string]tfexec.OutputMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Output indicates an expected call of Output.
func (mr *MockExecutorMockRecorder) Output(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockExecutor)(nil).Output), varargs...)
}

// SetStderr mocks base method.
func (m *MockExecutor) SetStderr(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", w)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockExecutorMockRecorder) SetStderr(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockExecutor)(nil).SetStderr), w)
}

// SetStdout mocks base method.
func (m *MockExecutor) SetStdout(w io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", w)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockExecutorMockRecorder) SetStdout(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockExecutor)(nil).SetStdout), w)
}

// SetWaitDelay mocks base method.
func (m *MockExecutor) SetWaitDelay(d time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWaitDelay", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWaitDelay indicates an expected call of SetWaitDelay.
func (mr *MockExecutorMockRecorder) SetWaitDelay(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWaitDelay", reflect.TypeOf((*MockExecutor)(nil).SetWaitDelay), d)
}

// MockExecutorFactory is a mock of ExecutorFactory interface.
type MockExecutorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorFactoryMockRecorder
	isgomock struct{}
}

// MockExecutorFactoryMockRecorder is the mock recorder for MockExecutorFactory.
type MockExecutorFactoryMockRecorder struct {
	mock *MockExecutorFactory
}

// NewMockExecutorFactory creates a new mock instance.
func NewMockExecutorFactory(ctrl *gomock.Controller) *MockExecutorFactory {
	mock := &MockExecutorFactory{ctrl: ctrl}
	mock.recorder = &MockExecutorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorFactory) EXPECT() *MockExecutorFactoryMockRecorder {
	return m.recorder
}

// NewTerraform mocks base method.
func (m *MockExecutorFactory) NewTerraform(workingDir, execPath string) (Executor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTerraform", workingDir, execPath)
	ret0, _ := ret[0].(Executor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewTerraform indicates an expected call of NewTerraform.
func (mr *MockExecutorFactoryMockRecorder) NewTerraform(workingDir, execPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTerraform", reflect.TypeOf((*MockExecutorFactory)(nil).NewTerraform), workingDir, execPath)
}

// MockInstaller is a mock of Installer interface.
type MockInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockInstallerMockRecorder
	isgomock struct{}
}

// MockInstallerMockRecorder is the mock recorder for MockInstaller.
type MockInstallerMockRecorder struct {
	mock *MockInstaller
}

// NewMockInstaller creates a new mock instance.
func NewMockInstaller(ctrl *gomock.Controller) *MockInstaller {
	mock := &MockInstaller{ctrl: ctrl}
	mock.recorder = &MockInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstaller) EXPECT() *MockInstallerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockInstaller) Install(ctx context.Context, dir, version, apiBaseURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, dir, version, apiBaseURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockInstallerMockRecorder) Install(ctx, dir, version, apiBaseURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockInstaller)(nil).Install), ctx, dir, version, apiBaseURL)
}

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPClient)(nil).Do), req)
}
