name: pr-ut

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pr-ut.yml'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
  merge_group:
    branches:
      - main
    paths:
      - '.github/workflows/pr-ut.yml'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Unit test
      shell: bash
      run: make ut
